name: medical_tracker
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  url_launcher: ^6.2.2
  permission_handler: ^11.0.1
  flutter_local_notifications: ^16.3.0
  workmanager: ^0.5.2
  timezone: ^0.9.2
  flutter_phone_direct_caller: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.1
  google_fonts:

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/play_store_512.png"

flutter:
  uses-material-design: true
